pkg/productinfo/gce/productinfo_gce.go

Add missing region from list (https://cloud.google.com/compute/docs/regions-zones/)

Add missing region

---

.circleci/config.yml
Makefile

Deps - updated makefile, ci config file

---

internal/app/productinfo/api/routes.go
pkg/productinfo/alibaba/productinfo_alibaba.go
pkg/productinfo/productinfo.go

- Added more logs to ease debugging
- alibaba client: enable async, increased goroutine pool size
- reorganized code around error handling to be more explicit

bugfixing, logging

---

README.md
cmd/productinfo/main.go
cmd/productinfo/main_test.go
docker-compose.yml
pkg/productinfo/alibaba/productinfo_alibaba.go

* renamed providers to allow proper service naming
* updated the readme

provideres ec2, gce renamed to amazon, google

---

docker-compose.yml
internal/app/productinfo/api/handlers.go
internal/app/productinfo/api/types.go

- minor fixes in response assembly - the generated client can unmarshal the responses properly

fixed service related responses

---

pkg/logger/logger.go
pkg/logger/logger_test.go

- embedded the FieldLogger interface into the ContextLogger to support all logging operations
- added unit test for checking the configuration

full support for logrus logging, unit testing

---

Gopkg.lock
internal/app/productinfo/api/handlers.go
pkg/productinfo/oracle/client/ce.go
pkg/productinfo/oracle/client/compute.go
pkg/productinfo/oracle/client/helper.go
pkg/productinfo/oracle/client/supported.go
pkg/productinfo/oracle/productinfo_oci.go
pkg/productinfo/productinfo.go
pkg/productinfo/types.go

oke service/region/images support

---

cmd/productinfo/build.go
cmd/productinfo/main.go
internal/app/productinfo/api/routes.go
internal/app/productinfo/api/types.go
main-targets.mk
pkg/logger/logger_test.go
pkg/productinfo/productinfo_test.go

- added new endpoint for retrieving build and version information
- the information also logged on application start
fixes #87

added endpoint for retrieving version / build information

---

.circleci/config.yml
Makefile
cmd/productinfo/main.go
internal/app/productinfo/api/routes.go
internal/app/productinfo/api/types.go
internal/platform/buildinfo/buildinfo.go
pkg/productinfo/azure/productinfo_azure.go

* using the agreed package structure for implementing the build / version info
* added missing test step to the CI config

refactored buildinfo package + added test step and fixes 

---

Dockerfile
entrypoint.sh
web/src/app/products/products.component.html
web/src/app/products/products.component.ts

Basepath fixes

---

pkg/productinfo/alibaba/productinfo_alibaba.go

* use the proper service name abbreviation for ` Alibaba Cloud Container Service for Kubernetes `

renamed ack service

---

pkg/productinfo/google/productinfo_google.go

add 2 machine type to google

---

pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/types.go

cleaned the driving of periodic renewal of cloud information

added Scraper interface

---

pkg/cloudinfo/executor.go
pkg/cloudinfo/executor_test.go
pkg/cloudinfo/types.go

* organized out executor implementation for better transparency 
* added test cases (rather some sort of example usage)
(no functionality changes)

extracted executor into a new file, added tests

---

Gopkg.lock
Gopkg.toml
internal/app/cloudinfo/api/classifier.go
internal/app/cloudinfo/api/errorresponse.go
internal/app/cloudinfo/api/handlers.go
internal/app/cloudinfo/api/routes.go
internal/app/cloudinfo/api/types.go
internal/app/cloudinfo/api/validate.go
internal/app/cloudinfo/api/validate_test.go
internal/app/cloudinfo/problems/problems.go
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/cloudinfo_test.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/types.go

* added context to errors (to the provider aggregation layer, more to come)
* methods reorganized to better reflect the logic in them
* CachedCloudInfo implements the CloudInfo interface - using the interface where appropriate
* removed validation middleware - providers / services / regions /attributes / zones validated in the router (also fixed some of the validators - bugfixes!)
* integrated error classifier and error responser into the handlers
relates to: #107

contextual errors + error responder

---

Gopkg.lock
Gopkg.toml
api/openapi-spec/cloudinfo.json
api/openapi-spec/cloudinfo.yaml
cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
configs/service-data.yaml
configs/services.yaml
internal/app/cloudinfo/api/handlers.go
internal/app/cloudinfo/api/types.go
internal/app/cloudinfo/loader/config.go
internal/app/cloudinfo/loader/data.go
internal/app/cloudinfo/loader/events.go
internal/app/cloudinfo/loader/loader.go
internal/app/cloudinfo/loader/loader_test.go
internal/app/cloudinfo/loader/manager.go
pkg/cloudinfo-client/models/product_details.go
pkg/cloudinfo-client/models/service.go
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/cistore.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/cloudinfo_test.go
pkg/cloudinfo/events.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/infoer.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/scrape.go
pkg/cloudinfo/types.go

This pull request is based on #149 
- fixes #147
- add service to zone cache
- remove attribute cache
- contains a basic PKE config

import static cloud information (service)

---

pkg/cloudinfo/cistore.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/scrape.go

What's in this PR?
- before updating cache, delete the previous content
- google region fix

delete obsolete cache data

---

pkg/cloudinfo/alibaba/cloudinfo.go

new kubernetes version fro ack

updated supported kubernetes version for ack

---

.circleci/config.yml

Change circleci config to
* use workflow
* run jobs in parallel
* run integration tests

Circleci workflow

---

pkg/cloudinfo/alibaba/cloudinfo.go

fixed alibaba scrape

---

web/src/app/products/products.component.html
web/src/app/products/products.component.scss
web/src/styles.scss

Redesign selectors/inputs

---

pkg/cloudinfo/alibaba/cloudinfo.go

In some cases, slice bounds out of range, so Cloudinfo got panic.

fixed alibaba getOnDemandPrice method

---

cmd/cloudinfo/config.go

Fix environment variable mapping in Viper

Fix env vars

---

.gen/api/graphql/exec.go
api/graphql/schema.graphql
gqlgen.yml
internal/cloudinfo/instance_type.go
main-targets.mk
pkg/cloudinfo/types.go

- added filtering by instance category (similarly to the network category implementation)
- four categories supported for the time being:
GENERAL_PURPOSE
MEMORY_OPTIMIZED
STORAGE_OPTIMIZED
COMPUTE_OPTIMIZED

Instance filtering by instance category

---

cmd/cloudinfo/config.go

fixed app.address

---

api/graphql/.graphqlconfig

Add alpha graphql config

---

.dockerignore
Dockerfile
docker-entrypoint.sh

Improve dockerfile

---

web/src/app/products/products.component.html

Fix continent api revert

---

Makefile

Fix version variable in makefile

Fix version variable in makefile

---

Makefile
main-targets.mk

* swagger installed properly to the project's bin folder
* go modules switched off for these commands
fixes #213

fix swagger generators

---

configs/amazon-service-data.yaml

fixes the supported Amazon PKE instance type list

add instance type list to amazon PKE

---

.circleci/config.yml
charts/cloudinfo/.helmignore
charts/cloudinfo/Chart.yaml
charts/cloudinfo/README.md
charts/cloudinfo/templates/NOTES.txt
charts/cloudinfo/templates/_helpers.tpl
charts/cloudinfo/templates/configmap.yaml
charts/cloudinfo/templates/deployment.yaml
charts/cloudinfo/templates/ingress.yaml
charts/cloudinfo/templates/secrets.yaml
charts/cloudinfo/templates/service-metrics.yaml
charts/cloudinfo/templates/service-monitor-price.yaml
charts/cloudinfo/templates/service-monitor-spotprice.yaml
charts/cloudinfo/templates/service-monitor.yaml
charts/cloudinfo/templates/service.yaml
charts/cloudinfo/values.yaml

Move helm chart to the repository
I would like to further improve the chart and add testing to it in a subsequent PR.

Move helm chart to the repository 

---

.circleci/config.yml

Fix chart ci config

---

configs/azure-service-data.yaml
pkg/cloudinfo/azure/cloudinfo.go

update azure PKE, get price info in Africa

---

pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo_test.go

- fixes #221 
- Virtual Machine Sizes API is deprecated, use Resources Skus API

support Azure availability zones

---

configs/azure-service-data.yaml
pkg/cloudinfo/azure/cloudinfo.go

update azure PKE service data file

---

cmd/cloudinfo/config.go
config.toml.dist
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/azure/config.go
pkg/cloudinfo/oracle/client/client.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/oracle/config.go

Replace file path with configuration in case of Azure and Oracle

---

cmd/cloudinfo/config.go
config.toml.dist
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/alibaba/config.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo_test.go
pkg/cloudinfo/amazon/config.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/azure/config.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/google/config.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/oracle/config.go

I added back support for default fallback (and at the same time removed default env var names from config, fallback should handle it instead)

Improve provider configuration

---

cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
config.toml.dist

Make scraping optional

---

web/package-lock.json

npm audit output:
```
found 3 high severity vulnerabilities
```
After upgrade:
```
=== npm audit security report ===                        
found 0 vulnerabilities
in 44959 scanned packages
```

[WEB] Upgrade dependencies

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/templates/NOTES.txt

Fix ingress notes

---

cmd/cloudinfo/main.go
internal/platform/errorhandler/panic_handler.go

Add panic handler

---

charts/cloudinfo/templates/deployment.yaml

Fix scraper deployment label indentation

---

internal/app/cloudinfo/cistore/redis.go
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/infoer.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/types.go

* improve logging
* wrap error not to lose information
* remove unused type (and related methods)

minor fixes

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml

LoadBalancers are fixed on Azure with this verison.

pke: use 1.14.2 instead of 1.14.0

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml

change k8s verions 1.12.8, 1.13.6

---

README.md
cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
config.toml.dist
configs/services.yaml
go.mod
go.sum
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/digitalocean/cloudinfo.go
pkg/cloudinfo/digitalocean/config.go
web/src/app/constants/providers.ts
web/src/app/modules/home/components/product-list/product-list.component.ts

Add digitalocean provider

---

pkg/cloudinfo/digitalocean/cloudinfo.go

Fix digital ocean monthly price

---

pkg/cloudinfo/amazon/cloudinfo.go

Add new supported kubernetes versions for amazon eks service

add new supported k8s versions for amazon eks

---

pkg/cloudinfo/amazon/cloudinfo.go

fixed k8s versions on the versions api as well

fix eks k8s versions

---

web/package-lock.json
web/package.json

Security fixes

---

pkg/cloudinfo/amazon/cloudinfo.go

Update EKS versions to the latest supported with patch

Change eks version to valid semver format

---

main-targets.mk
pkg/cloudinfo/alibaba/category_mapper.go
pkg/cloudinfo/azure/category_mapper.go
pkg/cloudinfo/azure/cloudinfo.go

add machines to categories, fix Azure cpu numbers

---

pkg/cloudinfo/amazon/cloudinfo.go

Fix: return latest eks images

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml

| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes https://github.com/banzaicloud/pke-image/issues/3
Change latest supported PKE version in the configuration.
We don't want to support old version.

Change latest supported pke version

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/requirements.lock
charts/cloudinfo/requirements.yaml

Redis version update 7.1.0 -> 9.1.8

---

pkg/cloudinfo/amazon/cloudinfo.go

* add 2 new eks regions
* update supported k8s versions

Update aws-sdk library, add new supported (eks) regions, update supported k8s versions 

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

- fix redis cluster problem
- update app image version
- fix provider default values

Chart improvement

---

.circleci/config.yml

circleci: fix docker image tagging

---

go.mod
go.sum
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/scrape.go

* compute service not treated differently anymore
* alibaba sdk version bump
* remove superfluous code

fix the scraping logic

---

pkg/cloudinfo/amazon/cloudinfo.go

* updated the supported k8s versions

update eks kubernetes versions

---

pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo.go

* product details retrieval was erroneous in case of ack, eks

fix aks, ack product details retrieval

---

cmd/cloudinfo/main.go
internal/app/cloudinfo/api/routes.go
internal/app/cloudinfo/api/types.go
internal/app/cloudinfo/api/validate.go
internal/app/cloudinfo/cistore/go-cache.go
internal/app/cloudinfo/loader/loader.go
internal/app/cloudinfo/loader/manager.go
internal/app/cloudinfo/management/handler.go
internal/cloudinfo/cloudinfo.go
internal/cloudinfo/scrape.go

| Bug fix?        |yes
* path parameter validation was not correct (the validation error was misleading)
* error handling and logging has been improved
- testing

error handling and logging improvements (scraper and loader components)

---

Makefile
api/openapi-spec/cloudinfo.json
api/openapi-spec/cloudinfo.yaml
cmd/cloudinfo/main.go
internal/app/cloudinfo/api/classifier.go
internal/app/cloudinfo/api/handlers.go
internal/app/cloudinfo/api/types.go
internal/app/cloudinfo/loader/loader.go
internal/cloudinfo/cloudinfo.go
internal/cloudinfo/providers/amazon/cloudinfo.go
internal/cloudinfo/providers/amazon/cloudinfo_test.go
internal/cloudinfo/providers/amazon/image_helper.go
internal/cloudinfo/providers/amazon/network_mapper.go
internal/cloudinfo/providers/amazon/network_mapper_test.go
internal/cloudinfo/scrape.go
internal/cloudinfo/types/types.go

* PKE images are scraped from amazon
* support for filtering by (k8s)version, pkeVersion, os
(_eg.: api/v1/providers/amazon/services/pke/regions/eu-west-2/images?latestOnly=true&version=1.13.10_)

support for PKE image retrieval

---

docs/management/management.md

Fix default management port

---

.gitignore
api/openapi-spec/cloudinfo.json
api/openapi-spec/cloudinfo.yaml
internal/app/cloudinfo/api/handlers.go
internal/app/cloudinfo/api/types.go

- fix inconsistencies in the api spec and implementsation
- made the responses more readable in case of image and versions retrieval

improve responses in case of images and versions retrieval

---

.circleci/config.yml

circleci: fix permission denied error

---

web/package-lock.json
web/package.json

Update web dependecy
To solve vuln issue

[web] update angular-devkit/build-angular dependecy

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

image version update to latest release in charts

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml

new supported pke k8s versions

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| Related tickets | fixes #X, partially #Y, mentioned in #Z
Updated the supported kubernetes vesions for Amazon EKS
Amazon has updated the maintained k8s versions dor EKS

update supported eks kubernetes versions

---

Dockerfile
package-lock.json
web/package-lock.json
web/package.json

Raise minimist version due to security concerns

Raise minimist version

---

web/package-lock.json
web/package.json

Add strange build dep

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

update app version

---

cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
config.toml.dist
configs/services.yaml
configs/vsphere-service-data.yaml
go.mod

Add vSphere provider, with a list of supported k8s version for PKE.

add vsphere provider

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

bump chart versions

---

internal/cloudinfo/providers/amazon/cloudinfo.go

Fix Amazon EKS pricing:
https://aws.amazon.com/about-aws/whats-new/2020/01/amazon-eks-announces-price-reduction/

Fix Amazon EKS pricing

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

bump and fix image versions

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

bump image version

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml
configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

Supported k8s version in PKE service

PKE support k8s version 20200414

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml
configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

Update pke k8s versions

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml
internal/cloudinfo/providers/alibaba/cloudinfo.go

fix ack version list (user error)

ack k8s version fix

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| Related tickets | https://github.com/banzaicloud/pipeline/pull/2957
Remove EKS 1.13 and bump 1.15 to 1.15.11

Update eks version

---

.idea/runConfigurations/Debug.xml

Fix goland build task

---

Dockerfile

Pin alpine version

---

internal/cloudinfo/providers/amazon/cloudinfo.go

Add EKS 1.16 support

---

web/package-lock.json
web/package.json

Add manually the security issued dep

---

internal/app/cloudinfo/api/routes.go

Fixes URLs ending in a trailing slash

Fix trailing slash in URL

---

.gitignore
Dockerfile
Makefile
cmd/cloudinfo/main.go
doc.go
go.mod
go.sum
internal/app/cloudinfo/api/filesystem.go
internal/app/cloudinfo/api/routes.go
main-targets.mk

Replace packr with pkger
Pkger is the new way of embeding static assets into a binary.

Replace packr with pkger

---

.dockerignore
internal/app/cloudinfo/api/routes.go

Fix index.html lookup

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

| Related tickets | https://github.com/banzaicloud/pke-image/pull/16  https://github.com/banzaicloud/pipeline/pull/2984
Update PKE k8s versions
(PKE was tagged to 0.5.1 and images were built)

Update k8s versions in case of PKE

---

internal/cloudinfo/scrape.go

| Related tickets | fixes #297
Change the error handling while scraping to report the error but continue, failing the overall scrape with the last error encountered.
This addresses #297 which I have also run into - it seems that two specific regions (ap-east-1 and me-south-1) both get 401s while all other regions work with an IAM user permissioned as per the guide. This allows cloudinfo to work fully for all other regions rather than scraping nothing for the whole of AWS.
Tested by scraping using valid and invalid credentials - product store is now populated as expected with the exception of the regions having specific …

Continue scraping if failures encountered on specific regions

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| New feature?    |yes
| Related tickets | https://github.com/banzaicloud/pipeline/pull/3009
EKS 1.17 support

EKS 1.17 support

---

internal/cloudinfo/providers/google/cloudinfo.go

Add `GKE Control Plane` instance to product list. 
This is necessary for https://github.com/banzaicloud/telescopes to recommend master instance.

Add GKE Control Plane instance to products

---

go.mod
go.sum
internal/cloudinfo/providers/amazon/cloudinfo_test.go

Upgrade AWS SDK
The gov cloud region description is old in the currently used version.

Upgrade aws sdk

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

| Related tickets | https://github.com/banzaicloud/pke-image/pull/18
Update K8s versions in the case of PKE.
Can be deployed if the pke-image build is completed.

Update K8s version in the case of PKE

---

internal/app/cloudinfo/api/handlers.go

Return an empty list when no images are found

Return an empty list when no images are found

---

internal/cloudinfo/providers/amazon/cloudinfo.go

Add support for pke gpu tag

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| Related tickets | https://github.com/banzaicloud/pipeline/pull/3066 , https://github.com/banzaicloud/cloudinfo/issues/355
Update K8s versions in case of EKS

Update eks k8s versions

---

go.mod
go.sum

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
| Related tickets | N/A
Update alibaba sdk to support cn-wulanchabu region.
https://github.com/aliyun/alibaba-cloud-sdk-go/commit/11be9f289181a0e1ea9fc2c5e6c7ba7d06c68a23
```json
{"application":"cloudinfo","component":"scraping-manager","environment":"production","error":"failed to retrieve zones for region: DescribeZones API call problem: SDK.ServerError\nErrorCode: InvalidOperation.NotSupportedEndpoint\nRecommend: \nRequestId: B7EF83F4-34DE-4186-9AB4-F345DAD6EB64\nMessage: The specified endpoint can't operate this region. Please use API DescribeRegions to get the …
```

update alibaba sdk to support cn-wulanchabu region

---

README.md

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
| Related tickets | N/A
Extend the PR with some instructions to be able to run the project locally.
The Angular project is required to be built.

docs: extend README with npm instructions for local development

---

internal/cloudinfo/providers/alibaba/ecs_endpoints.go
internal/cloudinfo/providers/alibaba/requests.go

Better endpoint detection for requests.
See https://github.com/aliyun/alibaba-cloud-sdk-go/issues/440

Fix Alibaba endpoint issue

---

go.mod
go.sum
internal/cloudinfo/providers/amazon/cloudinfo.go

| Related tickets | fixes #365
Fixes EU pricing info

Fix EU pricing

---

go.mod
go.sum

Upgrade aliyun SDK

---

cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
config.toml.dist
configs/amazon-service-data.yaml
internal/app/cloudinfo/loader/loader.go
internal/cloudinfo/providers/amazon/cloudinfo.go
internal/cloudinfo/providers/amazon/cloudinfo_test.go
internal/cloudinfo/providers/amazon/config.go

| Related tickets | fixes #351
Add support for multiple AWS partitions
To support AWS GovCloud

Add support for multiple AWS partitions

---

internal/cloudinfo/providers/google/cloudinfo.go

This reverts commit e520f94fe95db93a47659326324902bcc965caf2.
It doesn't work well

Revert "add GKE Control Plane instance to products"

---

web/package-lock.json
web/package.json

Add newer version of serialize-javascript cause of security issue.

Security update of serialize-javascript npm package

---

.licensei.toml

Fix license check

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| New feature?    |yes
| Related tickets | related: https://github.com/banzaicloud/pipeline/issues/3256 , https://github.com/banzaicloud/pipeline/pull/3279
Add EKS 1.18 support

feat(eks): EKS 1.18 support

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

Update PKE versions

---

.github/workflows/.editorconfig
.github/workflows/docker.yaml

Add docker build

---

web/package-lock.json
web/package.json

Fixing webpack-subresource-integrity security issue

Add higher version of webpack-subresource-integrity

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

feat: update chart and app version

---

web/src/app/constants/providers.ts
web/src/app/modules/home/components/product-list/product-list.component.ts

Remove oracle as provider from the frontend part of the application

[Feature]Remove oracle

---

web/src/app/constants/providers.ts
web/src/app/modules/home/components/product-list/product-list.component.ts

Reverts banzaicloud/cloudinfo#391

Revert "[Feature]Remove oracle"

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

| Related tickets | related: https://github.com/banzaicloud/pke-image/pull/24
Bump PKE K8s versions

Bump PKE K8s versions

---

README.md

Delete obsolete try pipeline reference

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| New feature?    |no
| Related tickets | partially https://github.com/banzaicloud/pipeline/issues/3438
Update supported versions

eks: update supported K8s versions

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| Related tickets | fixes #517 
Update supported EKS major versions.

update EKS versions

---

.github/workflows/ci.yaml

Fixed licensei auth in GitHub Actions CI.
Licensei might run into rate limiting without auth, so I used the GitHub token to auth it, but originally only added the env var to the cache step, which I now extended to the list and check steps as well.
Retrying rate-limited failed jobs might also work.
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~

Fixed licensei auth in GitHub Actions CI

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/values.yaml

Updated app (0.17.1->0.17.2) and chart (0.8.4->0.8.5) version.

Updated chart and app version

---

internal/cloudinfo/providers/amazon/cloudinfo.go

Added EKS K8s 1.22 version to the list of available versions, made 1.21 as default.
To be up-to-date with the versions supported by AWS and Pipeline.

Updated supported EKS K8s versions

---

main-targets.mk

Fixed golangci-lint download URL
Content has been moved

Fixed golangci-lint download URL

---

internal/cloudinfo/providers/amazon/cloudinfo.go

- updated latest supported EKS K8s patch versions
- added EKS K8s 1.23 version to the list of available versions
- made 1.22 as default K8s version
To be up-to-date with the versions supported by AWS and Pipeline.

Updated supported EKS versions (1.22->1.23)

---

charts/cloudinfo/values.yaml
cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
config.toml.dist
internal/app/cloudinfo/loader/manager.go
internal/cloudinfo/distribution/config.go

Added config options to disable PKE distribution on Azure and AWS (these remained enabled by default), so these options won't appear on the Pipeline GUI either.
It is nice to have more configuration options, also PKE on Azure is currently misbehaving, and we decided to drop support for now.
Tested locally.

Option to disable PKE on Azure and AWS

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml

| Deprecations?   | yes
Updated available and default K8s versions in correspondence of the currently default PKE 0.9.3 version.
So these versions appear correctly on Pipeline GUI.
Tested locally.

Update with PKE 0.9.3

---

.github/workflows/docker.yaml

Fixed GHA IFS handling in env var.
I messed it up on the GHA set-output migration.
Tested locally the bash commands, worked well.

Fixed GHA IFS handling in env var

---

internal/cloudinfo/providers/amazon/cloudinfo.go

Added EKS 1.24, removed EKS 1.19-20 support.
Also some auto formatting changes.
To support EKS K8s versions AWS currently supports.

Added EKS 1.24, removed EKS 1.19-20 support

---

.licensei.toml

Ignored jwt-go licence check
So the CI/CD pipeline wont't break

Ignored jwt-go licence check

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/templates/ingress.yaml
charts/cloudinfo/values.yaml

- Updated app version 0.17.2->0.18.0, chart version 0.8.5->0.9.0
- Updated Ingress version extensions/v1beta1 -> networking.k8s.io/v1
Te keep up with the latest EKS and K8s versions.

Updated chart 0.8.5->0.9.0
