banzaicloud/cloudinfo

api/openapi-spec/productinfo.json
api/openapi-spec/productinfo.yaml
pkg/productinfo-client/models/product_details.go
pkg/productinfo/ec2/productinfo_ec2.go
pkg/productinfo/ec2/productinfo_ec2_test.go
pkg/productinfo/productinfo.go

instance generation information added to product info - applies to ec2 only
- regenerated swagger
- regenerated pi client
- fxed tests
- tested locally

Instance type generation information in product info

---

pkg/productinfo/oci/productinfo.go
pkg/productinfo/types.go

Oracle - Remove ondemand prices shown as spot ones. Oracle doesn't have spot instances.
Make spotPrice omitted in the JSON response if empty.

Oracle - Remove ondemand prices shown as spot ones

---

internal/app/productinfo/api/routes.go
internal/app/productinfo/api/types.go
internal/app/productinfo/api/validate.go

- path parameter validation made more generic
- provider, service, region path parameters checked
- using api parameter structs for validation too (insted of internally defined structs)
fixes #58

Validate path parameters - service

---

cmd/productinfo/main.go
logger/logger.go
logger/logger_test.go
logger/middleware.go
pkg/productinfo/productinfo.go

- Original values were overwritten in the toctx method
- the logger framework is always initialized
- basic test for the logger package (to be extended!!!)

Parent context values taken into account when creating new contexts

---

Makefile
cmd/productinfo/main.go
pkg/logger/logger.go
pkg/logger/logger_test.go

- fixed the handling of fields in the contextlogger
(fields from the parent context weren't copied over - and overridden if  necessary)
- added unit tests

fixed parent context field inheritance

---

cmd/cloudinfo/main.go
pkg/cloudinfo/alibaba/network_mapper.go
pkg/cloudinfo/amazon/network_mapper.go
pkg/cloudinfo/amazon/network_mapper_test.go
pkg/cloudinfo/azure/network_mapper.go
pkg/cloudinfo/cistore.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/cloudinfo_test.go
pkg/cloudinfo/google/network_mapper.go
pkg/cloudinfo/infoer.go
pkg/cloudinfo/oracle/network_mapper.go
pkg/cloudinfo/types.go

The cloud info store is a repository (in memory cache) where the product information is stored.
* the store related interface is cleaned and extracted
* storage operations and cache key related logic moved to the specialized store implementation
* deleted a few unit tests which seemed to be hard to maintain and the covered functionality was simple

cleaned the cloud info store

---

Gopkg.lock
Gopkg.toml
cmd/cloudinfo/config.go
cmd/cloudinfo/main.go
cmd/cloudinfo/vars.go
internal/app/cloudinfo/api/handlers.go
internal/app/cloudinfo/api/validate.go
internal/platform/log/config.go
internal/platform/log/logger.go
internal/platform/log/standard_logger.go
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/alibaba/cloudinfo_test.go
pkg/cloudinfo/alibaba/config.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo_test.go
pkg/cloudinfo/amazon/config.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo_test.go
pkg/cloudinfo/azure/config.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/cloudinfo_test.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/google/config.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/oracle/config.go
pkg/cloudinfo/oracle/itra.go
pkg/logger/logger.go
pkg/logger/logger_test.go
pkg/logger/middleware.go

This PR is part of
* application configuration represented by a dedicated struct (populated by viper from various sources: flags, env ...)
* logging integrated through logur (and properly configured from the configuration)
* removed the non-standard ContextLogger interface; using contextual logging instead
* introduced config struct to manage application configuration
* provider specific infoer configurations separated fro better maintainability - thes are populated through viper during app initialization
relates to #107

configuration  cleanup

---

Gopkg.lock
cmd/cloudinfo/main.go
internal/app/cloudinfo/api/routes.go
internal/app/cloudinfo/api/types.go
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/cistore.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/cloudinfo_test.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/infoer.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/oracle/itra.go
pkg/cloudinfo/scrape.go
pkg/cloudinfo/types.go

* generic cloud info scraping logic has been factored out to specialized components:
** scrapingManager - in charge for scraping one provider and storing the processed result in the store (for a single provider)
** scraping driver - in charge for scheduling the scraping process
With this the CachingCloud info implementation has been freed up of these tasks - it can "focus" on serving requests through handlers ...
* unexported unnecessarily exported structs
* removed outdated ctx logger from the renewal / scraping components
* partially removed deprecated code (from the cloudinfo implementation) -some leftovers still ther not to break actual functionality
* refined tracing (with the new structure it's possible to have more accurate spans!)

Extracted product information gathering logic

---

Gopkg.lock
api/openapi-spec/cloudinfo.json
api/openapi-spec/cloudinfo.yaml
pkg/cloudinfo-client/models/product_details.go
pkg/cloudinfo/alibaba/category_mapper.go
pkg/cloudinfo/alibaba/cloudinfo.go
pkg/cloudinfo/alibaba/network_mapper.go
pkg/cloudinfo/amazon/cloudinfo.go
pkg/cloudinfo/amazon/network_mapper.go
pkg/cloudinfo/amazon/network_mapper_test.go
pkg/cloudinfo/azure/category_mapper.go
pkg/cloudinfo/azure/cloudinfo.go
pkg/cloudinfo/azure/cloudinfo_test.go
pkg/cloudinfo/azure/network_mapper.go
pkg/cloudinfo/cloudinfo.go
pkg/cloudinfo/google/cloudinfo.go
pkg/cloudinfo/google/network_mapper.go
pkg/cloudinfo/oracle/cloudinfo.go
pkg/cloudinfo/oracle/network_mapper.go
pkg/cloudinfo/types.go

Classify instance types into 5 different categories (General purpose, Compute optimized, Memory optimized, GPU instance, Storage optimized). Telescopes will be able to filter by category.

 add category to virtual machines

---

main-targets.mk
pkg/cloudinfo/amazon/cloudinfo.go

* remove supported k8s versions 1.10, 1.11 for eks (some of the spotguides require higher k8s versions)

remove supported k8s versions 1.10, 1.11 for eks

---

api/openapi-spec/cloudinfo.json
api/openapi-spec/cloudinfo.yaml
internal/app/cloudinfo/api/types.go

| Related tickets | fixes #X, partially #Y, mentioned in #Z
Return type of getVerions endpoint was wrongly annotated,, thus the generated OpenAPI spec is not correct.

fix return type for getVersions endpoint

---

.circleci/config.yml

| Related tickets | fixes #265
Replace Docker Hub's auto build.
```
master -> banzaicloud/cloudinfo:master
tag    -> banzaicloud/cloudinfo:<tag> & banzaicloud/cloudinfo:latest
branch -> only build
```

Build docker image with CircleCI

---

internal/app/cloudinfo/loader/data.go
internal/app/cloudinfo/loader/loader.go

| Bug fix?        |yes
| Deprecations?   |yes
Fixed loading of VMs in case there are no VMs specified in the configuration file
"Inherited" VMs were not stored for the PKE service

Pke loader fix

---

internal/cloudinfo/providers/amazon/image_helper.go

| Bug fix?        |yes
| API breaks?     | yes
fixes the name filter when describing images
due to the invalid filter no images were found while scraping
fixes #287

fix name filter while describing eks images

---

cmd/cloudinfo/config.go

API breaks?     | no
| Related tickets | fixes #295
AWS credentials are bound from the env
AWS credentials specified as env vars wer not taken into account while configuring the app

bound amazon credential envVars into the app config

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| Bug fix?        |yes
| Related tickets | #323 
Remove EKS version 1.13 from GetServiceImages function as well.

Remove EKS version 1.13 from GetServiceImages

---

.circleci/config.yml

circleci: fix docker image build when branch name contains `/`

---

charts/cloudinfo/Chart.yaml
charts/cloudinfo/requirements.lock
charts/cloudinfo/requirements.yaml
charts/cloudinfo/values.yaml

| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
- Bump redis chart version to 10.5.7 (kind: statefulset in version apps/v1 instead of apps/v1beta2) 
- Update cloudinfo version

Bump redis chart version

---

cmd/cloudinfo/main.go
internal/app/cloudinfo/cistore/cassandra.go
internal/app/cloudinfo/cistore/go-cache.go
internal/app/cloudinfo/cistore/redis.go
internal/cloudinfo/store.go

| Related tickets | fixes #336 
Introduces a Ready function to the CloudInfoStore interface and checks on start that this returns true for the configured product store, failing with an appropriate message.
Implements Ready for Cassandra (check a session can be created) and Redis (using the PING operation) to check the store is ready. For in-memory just returns true.
Tested by killing Redis then starting cloudinfo - can see it fail as expected:
```
INFO[0000] starting application                          application=cloudinfo arch=amd64 build_date="2020-06-23T12:58:36+0100" commit_hash=83911af compiler=gc …
```

Check product store is ready on startup

---

internal/cloudinfo/providers/amazon/image_helper.go

Filter listed PKE AMI images to be public and owned either by the account used for cloudinfo amazon scraping, or banzaicloud.

Filter PKE AWS AMI image owners

---

cmd/cloudinfo/config.go
config.toml.dist
internal/cloudinfo/providers/amazon/cloudinfo.go
internal/cloudinfo/providers/amazon/config.go

| Related tickets | fixes #350
Support for separate pricing credentials
The AWS Pricing API used for getting price information
about is only available in a small number of regions.
The primary account used for other resources
might not have access to those regions (eg. GovCloud).
For those cases, the price scraping client can
receive a different set of credentials.

Add support for separate pricing credentials

---

go.mod
go.sum
internal/cloudinfo/providers/alibaba/requests.go

We keep running into issues with the Alibaba provider complaining about missing regions when in fact the issue seems to be not going to the right endpoint for regional information.
Chances are we should use the ecs client instead of the sdk.
This PR attempts to fix these issues based on https://github.com/aliyun/alibaba-cloud-sdk-go/issues/440 and the ecs client, by setting the product code instead of the domain. The client should be able to determine the right domain.

Fix alibaba missing region issues

---

.circleci/config.yml

Fixes missing incubator repo and upgrades helm to v3.4.1.

ci: upgrade helm orb to 0.0.8

---

.github/workflows/ci.yaml

Fixed CI/GHA licensei cache.
It was broken.
I made a mistake by specifying the restore keys in a YAML array, then realized caching takes a multiline string, added the vertical pipe, but left the array dash prefixes in, messing up the restore keys on not hitting the full key.
(And it took me a while to notice it after I ruled out a couple other possibilities.)
[Here](https://github.com/banzaicloud/cloudinfo/runs/3126392643?check_suite_focus=true#step:6:17) is an example of the working restore key from this branch on a branch CI run.
- ~Related …

Fixed CI/GHA licensei cache

---

internal/cloudinfo/providers/amazon/cloudinfo.go

| Related tickets | fixes #656 
Add EKS K8s 1.21 support to Cloudinfo

Add EKS K8s 1.21 support to Cloudinfo

---

configs/amazon-service-data.yaml
configs/azure-service-data.yaml
configs/vsphere-service-data.yaml
internal/cloudinfo/providers/amazon/cloudinfo.go

| Deprecations?   | yes
Dropping support for old Kubernetes versions.
Converging to support the latest versions of Kubernetes, some upgrades made k8s versions older than 1.19 deprecated.
Tested locally

Removed unsupported k8s versions

---

.github/workflows/docker.yaml

Setting the container label org.opencontainers.image.source to the HTTPS URL of the repository instead of the SSH URL of it.
To try and fix the GHA access to the ghcr.io/banzaicloud/cloudinfo container repository and pacakges.
For some reason GHA lost access to the ghcr.io container registry somewhere in the past.
There is a confirmed fix to add GHA write access to the cloudinfo repository, at the ghcr.io package settings page, but the
org.opencontainers.image.source label should do the same when configured correctly.
For now I'm trying to set it to the HTML URL (HTTPS) instead of the clone URL (SSH). …

Attempt fixing the GHA container image access

---

.github/workflows/docker.yaml

Reverts banzaicloud/cloudinfo#844
Well that did not work. (More info in the original PR.)

Revert "Attempt fixing the GHA container image access"

---

internal/app/cloudinfo/api/handlers.go
internal/app/cloudinfo/api/types.go

Fixed image filtering for `gpu` tag, also added filtering for `cr` (container runtime) image tag that was introduced with PKE 0.9.3.
The correct images to be returned on request with these params.
Tested locally.

Filter for `gpu` and `cr` params
